//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookery.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionStep
    {
        public int StepID { get; set; }
        public string Description { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public int RecipeID { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
